export const MESSAGE_CREATED = 'MESSAGE_CREATED'
export const NEW_CONVERSATION = 'NEW_CONVERSATION'

export const IS_USER_ONLINE = 'IS_USER_ONLINE'

export const NOTIFICATION_CREATED_OR_DELETED = 'NOTIFICATION_CREATED_OR_DELETED'
